### ISSUE TITLE
Does it work with Minecraft demo version?

### ISSUE THREAD

**Issue by PrincipalsOffice** [ufoot/dogcraft#12]
I tried to follow the instructions and install everything under a macOS Sierra env with a demo version of Minecraft (created a launch option with 1.10.2).
First I started the pyminecraft server (no error), then I encoutnered the following error when I tried to run `./demo.sh`. Any idea what might went wrong for me?

Awesome project btw!

```
→ ./demo.sh
init api_key=xxxxxxxx... app_key=xxxxxxxxxxxx... api_host=https://app.datadoghq.com
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    mc = minecraft.Minecraft.create("172.86.162.69")
  File "/Users/jasonye/.pyenv/versions/3.6.0/envs/dogcraft/lib/python3.6/site-packages/mcpi/minecraft.py", line 171, in create
    return Minecraft(Connection(address, port))
  File "/Users/jasonye/.pyenv/versions/3.6.0/envs/dogcraft/lib/python3.6/site-packages/mcpi/connection.py", line 17, in __init__
    self.socket.connect((address, port))
TimeoutError: [Errno 60] Operation timed out
```
---

Edit: The timeout error disappeared after I changed line 20 of [main.py](https://github.com/ufoot/dogcraft/blob/master/main.py#L20) to `mc = minecraft.Minecraft.create()`, but a new error occured:
```
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    (len(dashboards), mc.player.getTilePos()))
  File "/Users/jasonye/.pyenv/versions/3.6.0/envs/dogcraft/lib/python3.6/site-packages/mcpi/minecraft.py", line 70, in getTilePos
    return CmdPositioner.getTilePos(self, [])
  File "/Users/jasonye/.pyenv/versions/3.6.0/envs/dogcraft/lib/python3.6/site-packages/mcpi/minecraft.py", line 41, in getTilePos
    s = self.conn.sendReceive(self.pkg + b".getTile", id)
  File "/Users/jasonye/.pyenv/versions/3.6.0/envs/dogcraft/lib/python3.6/site-packages/mcpi/connection.py", line 63, in sendReceive
    return self.receive()
  File "/Users/jasonye/.pyenv/versions/3.6.0/envs/dogcraft/lib/python3.6/site-packages/mcpi/connection.py", line 57, in receive
    raise RequestError("%s failed"%self.lastSent.strip())
mcpi.connection.RequestError: b'player.getTile()' failed
```
Pyminecraft also displayed the following error:
```
[23:55:46 INFO]: [RaspberryJuice] Starting input thread
[23:55:46 INFO]: [RaspberryJuice] Opened connection to/127.0.0.1:49379.
[23:55:46 INFO]: [RaspberryJuice] Starting output thread!
[23:55:46 WARN]: [RaspberryJuice] Error occured handling command
[23:55:46 WARN]: java.lang.NullPointerException
[23:55:46 WARN]: 	at net.zhuoweizhang.raspberryjuice.RemoteSession.handleCommand(RemoteSession.java:239)
[23:55:46 WARN]: 	at net.zhuoweizhang.raspberryjuice.RemoteSession.handleLine(RemoteSession.java:119)
[23:55:46 WARN]: 	at net.zhuoweizhang.raspberryjuice.RemoteSession.tick(RemoteSession.java:99)
[23:55:46 WARN]: 	at net.zhuoweizhang.raspberryjuice.RaspberryJuicePlugin$TickHandler.run(RaspberryJuicePlugin.java:155)
[23:55:46 WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
[23:55:46 WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[23:55:46 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723)
[23:55:46 WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[23:55:46 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[23:55:46 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[23:55:46 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[23:55:46 INFO]: [RaspberryJuice] Closed connection to/127.0.0.1:49379.
```

**Comment by PrincipalsOffice** [comment]
Closing, demo version won't work, need full version to connect to localhost.
